name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Exercício 1 - somar
      id: exercicio-1-somar
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Exercício 1 - somar
        setup-command: npm install
        command: npm test -- --testPathPattern=exercicio1
        timeout: 10
        max-score: 33
    - name: Exercício 2 - verificarIdade
      id: exercicio-2-verificaridade
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Exercício 2 - verificarIdade
        setup-command: ''
        command: npm test -- --testPathPattern=exercicio2
        timeout: 10
        max-score: 33
    - name: Exercício 3 - media
      id: exercicio-3-media
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Exercício 3 - media
        setup-command: ''
        command: npm test -- --testPathPattern=exercicio3
        timeout: 10
        max-score: 34
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        EXERCICIO-1-SOMAR_RESULTS: "${{steps.exercicio-1-somar.outputs.result}}"
        EXERCICIO-2-VERIFICARIDADE_RESULTS: "${{steps.exercicio-2-verificaridade.outputs.result}}"
        EXERCICIO-3-MEDIA_RESULTS: "${{steps.exercicio-3-media.outputs.result}}"
      with:
        runners: exercicio-1-somar,exercicio-2-verificaridade,exercicio-3-media
